---
label: services
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: file
  name: cover
  label: cover
- type: text
  name: permalink
  label: permalink
